### ISSUE TITLE
notes.pdf not included in git repo

### ISSUE THREAD

**Issue by frenchy64** [jsiek/B629-denotational#1]
By the readme, it seems `notes.pdf` should be present, but it's not.

**Comment by RyanGlScott** [comment]
True, we could check `notes.pdf` into the repo. But at the same time, this _is_ a frequently changing document that would need to be rebuilt and re-checked in every time the source changes—and it's a 255K binary file to boot. Perhaps we should simply change the repo advising people to build it from source? (At least until "v1.0".)

**Comment by pnwamk** [comment]
Would adding a `Makefile` be a reasonable middle ground?

**Comment by vikraman** [comment]
Another alternative is checking in the pdf using git-lfs which is natively supported on github. I do that with my paper repos, it works great!
